### ISSUE TITLE
After last update extension no longer working on macos

### ISSUE THREAD

**Issue by mosmetro** [dapetcu21/defold-fmod#10]
After last update extension no longer working on macos.

WARNING:fmod: dlopen(/Users/.../defold-fmod-master/build/x86_64-darwin/libfmod.dylib, 10): image not found
WARNING:fmod: dlopen(/Users/.../defold-fmod-master/build/x86_64-darwin/libfmodstudio.dylib, 10): image not found
WARNING:fmod: FMOD libraries could not be loaded. FMOD will be disabled for this session
Previously it working fine on Defold 1.2.144.

**Comment by dapetcu21** [comment]
v1.0.3 should fix this.

Try with this dependency URL:
https://github.com/dapetcu21/defold-fmod/archive/v1.0.3.zip
