### ISSUE TITLE
Not working on Android?

### ISSUE THREAD

**Issue by subsoap** [dapetcu21/defold-fmod#11]
Audio is not playing when it works on Windows

**Comment by subsoap** [comment]
Maybe file format issue? I'm not sure if that matters.

**Comment by dapetcu21** [comment]
Huh... I'll check it out, but in the meantime, make sure you're using the last version (1.0.3). Also, what Android version and phone are we talking about?

**Comment by subsoap** [comment]
So it seems it does work but I have the path wrong for the audio banks.

If this works for Windows what should I have it set for to work on Android?

```
fmod.studio.system:load_bank_file("./_assets/_fmod_banks/master.bank", fmod.STUDIO_LOAD_BANK_NORMAL)
fmod.studio.system:load_bank_file("./_assets/_fmod_banks/master.strings.bank", fmod.STUDIO_LOAD_BANK_NORMAL)
```

**Comment by subsoap** [comment]
By the way, in your example you have

```
 fmod.studio.system:load_bank_memory(resource.load("/banks/Master Bank.bank"), fmod.STUDIO_LOAD_BANK_NORMAL)
  fmod.studio.system:load_bank_memory(resource.load("/banks/Master Bank.strings.bank"), fmod.STUDIO_LOAD_BANK_NORMAL)
  fmod.studio.system:load_bank_memory(resource.load("/banks/Vehicles.bank"), fmod.STUDIO_LOAD_BANK_NORMAL)
```

These paths will not work on Windows. Do they work on OSX?

**Comment by subsoap** [comment]
I tested the defold-fmod example again and it does work fine. Still investing more why my version is not working... I think it is in part path, but possibly file format too, I'm not sure still.

**Comment by subsoap** [comment]
I switched the banks to a custom resource instead of a bundle resource and then used fmod.studio.system:load_bank_memory instead of fmod.studio.system:load_bank_file and then / style path with no ./ works. I'd still like to figure out how to get fmod.studio.system:load_bank_file to work on Android eventually. As long as it's not Android works. This can be closed.

**Comment by subsoap** [comment]
I think I was using load_bank_file to let FMOD manage the loading of the files into memory? I've not tested the memory impact of load_bank_memory. My bank files are about 50MB currently.

**Comment by subsoap** [comment]
Now there is noticeable lag when loading sounds / music on desktop platforms... so I'll try to get load_bank_file to work in the future on Android. If you have any ideas it would be helpful.

Related post https://forum.defold.com/t/bundle-resources-android-path-solved/43974/11

**Comment by subsoap** [comment]
I did some research and it seems like keeping the audiobank in memory can cause the crackling with larger files 

https://github.com/dapetcu21/defold-fmod/issues/17

I'll try to break my banks up more, and use load_bank_file again.

**Comment by subsoap** [comment]
Still struggling to get it to work right on Android

https://forum.defold.com/t/where-are-common-bundle-resources-supposed-to-be-put-in-android/51335/8

Currently seems to be a path issue somehow but I don't understand the problem

**Comment by subsoap** [comment]
Some progress on making it more memory efficient on Android https://github.com/subsoap/defold-fmod

**Comment by dapetcu21** [comment]
Hm... I'll give it a go

**Comment by subsoap** [comment]
@dapetcu21 Useful info?

https://webcache.googleusercontent.com/search?q=cache:EX8aUlkDK0cJ:https://www.fmod.com/docs/api/content/generated/platform_android/basics.html+&cd=4&hl=en&ct=clnk&gl=us

**Comment by subsoap** [comment]
@dapetcu21 any luck? If you can get this to work it would greatly reduce memory footprint on mobile which seems to be a source of crashing for us.

**Comment by subsoap** [comment]
I'll take another stab at it soon.

**Comment by subsoap** [comment]
So I think a problem that the resources are in the base.apk and so loading them is more complicated than simple file system paths. You can't link to files within an apk like you can any other directory. Still not sure how to do it properly because I don't know how fmod wants to be able to do it. I'm sure there's a way it's expecting to use to load files within the Android apk.

**Comment by subsoap** [comment]
The fmod site kind of sucks for docs, everything Google search leads to is a 404 and the old doc I found is no longer cached by Google orz.

**Comment by subsoap** [comment]
> FMOD5 (FMOD Studio) has this functionality built in, just prefix the filename with “file:///android_asset/” and it will load.

I did try that and it didn't work but maybe I wasn't doing ti right?

**Comment by subsoap** [comment]
https://1drv.ms/u/s!AloFCeaGxsVwgwB5jiAzE8IAURPL

![Screenshot_20190522-142559](https://user-images.githubusercontent.com/409170/58210431-39ecad80-7c9e-11e9-956d-31a4e5720967.jpg)

Test project where it's not working for me. There's got to be something small that I'm missing. 😩

**Comment by subsoap** [comment]
Currently I'm thinking about copying the bank files to an external folder which FMOD can actually load.

**Comment by dapetcu21** [comment]
I got it working. It's quite simple, actually:

<img width="337" alt="Screenshot 2019-06-07 at 18 48 50" src="https://user-images.githubusercontent.com/428060/59116740-eb553980-8954-11e9-83cb-50dcbdd7952b.png">

And then you load them like this:

```lua
  fmod.studio.system:load_bank_file("file:///android_asset/banks/Master Bank.bank", fmod.STUDIO_LOAD_BANK_NORMAL)
  fmod.studio.system:load_bank_file("file:///android_asset/banks/Master Bank.strings.bank", fmod.STUDIO_LOAD_BANK_NORMAL)
  fmod.studio.system:load_bank_file("file:///android_asset/banks/Vehicles.bank", fmod.STUDIO_LOAD_BANK_NORMAL)
```

**Comment by dapetcu21** [comment]
I'll write a section in the README

**Comment by subsoap** [comment]
So the mistake I was using was using common folder for bundle resources or something? Most of the rest is the same, or is this for FMOD 2.0?

**Comment by dapetcu21** [comment]
It's the same for both 1.x and 2.0. The mistake was that it wasn't in the `assets` subdirectory on Android. Check out https://github.com/dapetcu21/defold-fmod/tree/fmod2#loading-banks-from-the-file-system

**Comment by subsoap** [comment]
Awesome! So again restated

Needs to be in an assets sub-folder within the bundle resources folder.

![2019-06-08 11_44_52-Window](https://user-images.githubusercontent.com/409170/59151144-dc1ccd00-89e2-11e9-92ab-ef238026381d.png)

Then the loading path must start with "file:///android_asset/" which targets the assets folder.

```
	local extra_path = ""

	local bank1 = ""
	local bank2 = ""
	local bank3 = ""

	if is_editor() then
		extra_path = "./bundle_resources/common/assets"
		bank1 = (extra_path .. "/banks/Master Bank.bank")
		bank2 = (extra_path .. "/banks/Master Bank.strings.bank")
		bank3 = (extra_path .. "/banks/Vehicles.bank")
	elseif sys_info.system_name == "Android" then
		extra_path = "file:///android_asset/"
		bank1 = (extra_path .. "banks/Master Bank.bank")
		bank2 = (extra_path .. "banks/Master Bank.strings.bank")
		bank3 = (extra_path .. "banks/Vehicles.bank")
	else
		bank1 = directories.path_for_file(extra_path .. "assets/banks/Master Bank.bank")
		bank2 = directories.path_for_file(extra_path .. "assets/banks/Master Bank.strings.bank")
		bank3 = directories.path_for_file(extra_path .. "assets/banks/Vehicles.bank")
	end 
```
