### ISSUE TITLE
Document more

### ISSUE THREAD

**Issue by subsoap** [dapetcu21/defold-fmod#16]
I can help with this. The official FMOD docs are kind of annoying to browse through. I can make a list of commonly used commands and how to use them for Defold extension. Plus give tips on using FMOD studio.

**Comment by subsoap** [comment]
I guess wait until transition to v2 happens if it does.

**Comment by dapetcu21** [comment]
If we just copy paste some API docs, that's a waste of time. FMOD's API docs are decent and occasionally maintained. There's no point in duplicating information when we can just link to it. As for examples and tips, yes, those are very welcome.

**Comment by dapetcu21** [comment]
I'm closing this. Feel free to open PRs if you ever want to improve the examples or the docs.
