### ISSUE TITLE
Engine crashes when target from editor

### ISSUE THREAD

**Issue by subsoap** [dapetcu21/defold-fmod#18]
https://forum.defold.com/t/targeting-android-engines-with-some-native-extensions-make-them-crash/51333/4

**Comment by dapetcu21** [comment]
Hm... On what phone and Android version?

**Comment by subsoap** [comment]
Samsung Galaxy S8 SM-G950U

android version 9 API level 28

**Comment by subsoap** [comment]
Happens with entirely blank project which only includes the extension. LFS extension for example does not have the issue.

**Comment by subsoap** [comment]
Any luck with this one? Does it work for your devices to target them with the editor?

**Comment by dapetcu21** [comment]
yeah. i fixed this in 2.0
