### ISSUE TITLE
What should load_bank_file path be like for HTML5 builds?

### ISSUE THREAD

**Issue by subsoap** [dapetcu21/defold-fmod#23]
I have tried a few variations like  "./assets/banks/master.bank"

```
bank1 = "assets/banks/master.bank"
fmod.studio.system:load_bank_file(bank1, fmod.STUDIO_LOAD_BANK_NORMAL)
```

![path](https://user-images.githubusercontent.com/409170/64063472-6cfde180-cba9-11e9-8dce-1dcb8a2d51bf.png)

The bank file is there, it can be downloaded.

![2019-08-31 04_40_55-Downloads](https://user-images.githubusercontent.com/409170/64063491-91f25480-cba9-11e9-8555-2ec1fa124f7b.png)

**Comment by dapetcu21** [comment]
For HTML5, you should probably put them in custom_resources and load them with load_bank_memory.

**Comment by dapetcu21** [comment]
load_bank_file will load from the emscripten emulated file system. If you place them in bundled_resources, you'll have to download them yourself with JS and then load them with load_bank_memory. I think load_bank_memory takes either dmBuffers or plain Lua strings with data. Or just put them in custom_resources and load them with resource.load()

**Comment by subsoap** [comment]
I wish Defold made platform specific stuff like this easier to do...

For science I tested making the link absolute and it also didn't work but did give a different error.

![2019-08-31 04_45_26-Faerie Solitaire Harvest Free 1 1 19 8 24b](https://user-images.githubusercontent.com/409170/64063544-45f3df80-cbaa-11e9-859d-58624a79e067.png)

**Comment by subsoap** [comment]
>Or just put them in custom_resources and load them with resource.load()

How should this be done after? With fmod.studio.system:load_bank_memory or?

**Comment by dapetcu21** [comment]
Yeah. Look at the example. The banks there are loaded with resource.load()

**Comment by subsoap** [comment]
Switched over to load_bank_memory + resource.load + custom resources

![2019-08-31 05_02_33-Faerie Solitaire Harvest Free 1 1 19 8 24b](https://user-images.githubusercontent.com/409170/64063701-94a27900-cbac-11e9-89da-59f62172c050.png)


```ERROR:SCRIPT: A requested output, dsp unit type or codec was not available.```

The same setup works on Windows while testing. Any way to get specific info on the error?

**Comment by dapetcu21** [comment]
That's all the specific info there is. Check your bank export settings for the HTML5 banks. Maybe Chrome doesn't support the codec you're trying to use.

**Comment by subsoap** [comment]
Could these be an issue?

![2019-08-31 05_16_36-harvest-free fspro - Event Editor](https://user-images.githubusercontent.com/409170/64063827-93724b80-cbae-11e9-8ae8-16c35b40866b.png)
![2019-08-31 05_16_20-harvest-free fspro - Event Editor](https://user-images.githubusercontent.com/409170/64063828-93724b80-cbae-11e9-9866-63087967ae2a.png)

Do you mean these settings?

![2019-08-31 05_18_46-Preferences](https://user-images.githubusercontent.com/409170/64063843-df24f500-cbae-11e9-94eb-8843aa502330.png)

**Comment by dapetcu21** [comment]
I don't know. We didn't touch the encoding settings in our project and it works. Do you have this in you game.project:?

```
[fmod]
speaker_mode = stereo
```

**Comment by subsoap** [comment]
Yes

![2019-08-31 05_26_06-Faerie Solitaire Harvest Free - Defold Editor 2 0](https://user-images.githubusercontent.com/409170/64063906-db45a280-cbaf-11e9-9548-8d49b9e9f7c1.png)

The only other effect is

![2019-08-31 05_25_37-harvest-free2 fspro_ - Event Editor](https://user-images.githubusercontent.com/409170/64063909-e4367400-cbaf-11e9-970d-1fbd67359e0f.png)

I'm testing removing everything from a copy of the project to see if it works then.

**Comment by dapetcu21** [comment]
Our DSP chains are way more complicated than yours, so I don't think that should be the problem. But who knows, maybe HTML doesn't support all DSP types.

**Comment by subsoap** [comment]
Could you post your encoding settings?

**Comment by subsoap** [comment]
It works now so it must have been one of those things. Maybe the Multiband EQ?

![2019-08-31 05_32_22-Faerie Solitaire Harvest Free 1 1 19 8 24b](https://user-images.githubusercontent.com/409170/64063980-bc93db80-cbb0-11e9-8bb0-7da8a0c6e4a9.png)

**Comment by subsoap** [comment]
I accidentally deleted my "free" version of fmod project which I wasn't versioning... so I'll have to remake it later but I will try and test this later more too to figure out the exact cause of issue.

**Comment by subsoap** [comment]
Audio glitches / hangs same as playing audio from the engine whenever doing stuff. Must be because of the way the extension is built with the engine? So whenever the engine is busy doing something it makes the audio stop playing for a moment / repeat frames.

**Comment by dapetcu21** [comment]
It’s because there are no threads in JS, so audio processing must be done on the main thread in the update loop along with the rest of the engine’s work. This means that when the game is lagging, fmod doesn’t have the chance to fill up audio buffers and they underrun. There’s no good solution to this. You can try increasing the audio buffer size, though (The extension already makes them larger on HTML5 by default). Don’t know the fmod function by heart, but look through their platform-specific getting started manuals and you’ll find it there.

**Comment by subsoap** [comment]
This I think?

https://github.com/dapetcu21/defold-fmod/blob/master/bridge/src/fmod_init.c#L92

**Comment by subsoap** [comment]
```
ERROR:SCRIPT: A requested output, dsp unit type or codec was not available.
```
Had to visit this again, this error was caused by Multiband EQ. To solve it I played the sound in FMOD Studio and recorded it in Audacity, then replaced that setup with the recorded audio.

**Comment by subsoap** [comment]
Could you help with loading the bank directly and not including it in the game archive?

When testing FSH from Project -> Build HTML5 audio is pretty good, but the actual bundled version on a server has audio issues. I believe this is because of the bank being in the bundled archive. I've already disabled archive compression and that helps with general loading, but atm it seems clear loading the FMOD bank separately would work better for audio playback.

**Comment by dapetcu21** [comment]
I added control over `buffer_length` and `num_buffers` (see [setDSPBufferSize](https://fmod.com/resources/documentation-api?version=2.0&page=core-api-system.html#system_setdspbuffersize)). See if you can mitigate the stutteryness by playing with those numbers. It's set at 2 buffers of 2048 samples each by default on HTML5.

**Comment by subsoap** [comment]
Cool! Will test soon.
