### ISSUE TITLE
Potential crashes on iOS/Android

### ISSUE THREAD

**Issue by subsoap** [dapetcu21/defold-fmod#25]
> Harvest crashes constantly. On iPhone 8 with latest updates.
> Game keeps crashing so it is impossible to earn gold stars (Android  OnePlus5T)

![info](https://user-images.githubusercontent.com/409170/75374739-acb83400-5881-11ea-95e6-25b7bcc4b359.png)
![info2](https://user-images.githubusercontent.com/409170/75374785-bb065000-5881-11ea-8604-1247e7a6d156.png)

FMOD is the main native extension that is enabled in this game on both iOS and Android so it might be the cause. Still waiting on getting more info.

**Comment by dapetcu21** [comment]
Get your hands on a crash report if you can, symbolicate it and post it here. I've had Interrogation on my phone (6S) for a while now and didn't experience anything similar. Same on the testing iPad we have around the office.

**Comment by subsoap** [comment]
Testing comment

**Comment by subsoap** [comment]
I have an iPad 2, iPhone 5 and iPhone 6S and did not have any issues either. Our other games FSR doesn't have FMOD but does have the rest of the misc NEs that are shared between them, I asked the user who reported above (about FSH) to test FSR and he says it has not crashed once when testing in all of the same ways.

Will get the debug info as soon as I can.

**Comment by Brun0oO** [comment]
Hi,

When I try to target iOS device, I got "Your platform is not yet supported." if i build the example project.
I don't find the library for iOS in fmod/res folder, how can I target iOS device like you seem to do ?

**Comment by dapetcu21** [comment]
The iOS library is not in fmod/res, it's in fmod/lib. Where do you get that error message? I can successfully bundle and run the example project on iOS.

**Comment by dapetcu21** [comment]
Maybe you're trying to bundle for iOS from a Windows/Linux PC? 
That's not supported due to the way iOS code signing works. You need a Mac to build for iOS

**Comment by Brun0oO** [comment]
From my mac, I run "Project/Bundle/iOS Application..." and click on the "Create Bundle..." button then I got these errors :
```
/fmod/res/armv7-android/lib/arm64-v8a/libfmod.so
	The files' relative path conflict:
'/Users/bruno/Mobile game/fmod/res/armv7-android/lib/arm64-v8a/libfmod.so' and
'/Users/bruno/Mobile game/fmod/res/armv7-android/lib/arm64-v8a/libfmod.so
```
Perhaps, I forgot something in my project configuration because I started from a basic mobile project in which I try to add fmod. Why are android related things showing up at build time?
Before my attempt to add fmod, my basic mobile project launched correctly on my ios device. 
Similarly, I managed to run the example provided on github on my mac.

**Comment by Brun0oO** [comment]
@dapetcu21 : is there a way to send me your ios project even if it means redo the signing pass on my side?

**Comment by dapetcu21** [comment]
Sounds like you added the whole `fmod` folder to your project AND added the dependency URL. You're not supposed to do that. Just add the dependency URL and it will work. For running the game in the editor (as per the instructions in the README), you're only supposed to copy `fmod/res` not everything else (not `fmod/lib`, not `fmod/ext.manifest` and not `fmod/src`. delete those).

**Comment by Brun0oO** [comment]
It's good :o)
Starting from scratch, I managed to launch your project on my iOS terminal.
Now I will try to start from scratch from my basic project (by the way, I'm discovering how the Defold editor works...)
Thank you for helping me !

**Comment by dapetcu21** [comment]
I'm closing this old issue. @subsoap In case you're still having problems and have a reprocase / crash report, we can re-open it.
