### ISSUE TITLE
fmod architectures on Android and Windows

### ISSUE THREAD

**Issue by rsaienz** [dapetcu21/defold-fmod#26]
The fmod example project does NOT work (fmod is nil) on Android if only 64 bit is selected in the bundle options. It works if both 64 and 32 bit are selected.

Moreover the fmod.dll and fmodstudio.dll are not loaded (failed with error 193) on Windows with architecture 64 bit. On the other hand it works with 32 bit.

**Comment by subsoap** [comment]
@rsaienz Due to a Defold bundling error, you will need to manually place the correct DLL version for now depending on if you are bundling for 32bit or 64bit.

**Comment by dapetcu21** [comment]
No need. I just committed a workaround that bundles both DLL sets in a compatible way. I'll make a release once I test it on all platforms.

**Comment by rsaienz** [comment]
Great!

**Comment by dapetcu21** [comment]
Fixed in v2.4.4
